+----- main.py:15 -----+
| 2024.07.10-16:32:26  |
+----------------------+

+- /home/lzy/ltf/Codes/FLDefinder/master/src/utils/MyTimer.py:39 -+
| Start | 2024.07.10-16:32:27                                     |
+-----------------------------------------------------------------+

+- /home/lzy/.conda/envs/ltf/lib/python3.8/site-packages/torchvision/datasets/cifar.py:141 -+
| Tisfy: Files already downloaded and verified.                                             |
+-------------------------------------------------------------------------------------------+

+- /home/lzy/.conda/envs/ltf/lib/python3.8/site-packages/torchvision/datasets/cifar.py:141 -+
| Tisfy: Files already downloaded and verified.                                             |
+-------------------------------------------------------------------------------------------+

+- /home/lzy/ltf/Codes/FLDefinder/master/src/utils/MyTimer.py:39 -+
| init accuracy: 10.20% | 2024.07.10-16:32:36                     |
+-----------------------------------------------------------------+

+- /home/lzy/ltf/Codes/FLDefinder/master/src/utils/MyTimer.py:39 -+
| Round 1 of 32 | 2024.07.10-16:32:36                             |
+-----------------------------------------------------------------+

+---------------------- main.py:564 ----------------------+
| Average loss: 2.3675934791564943 | 2024.07.10-16:32:37  |
+---------------------------------------------------------+

+---------- main.py:435 ----------+
| PCA Begin | 2024.07.10-16:32:39 |
+---------------------------------+


下面ByHand：

Traceback (most recent call last):
  File "main.py", line 569, in <module>
    _, anomaList = gradentAnalyzer.find_useful_gradients(grads_dict)
  File "main.py", line 451, in find_useful_gradients
    useful_grads_list, anomalous_grads_list = self.PCA_isolation_Forest_Method(all_grads)
  File "main.py", line 436, in PCA_isolation_Forest_Method
    reduced_grads = self.pca.fit_transform(all_grads)  # 两次fit_transform会使用不同的主成分，而一次fit_transform后调用transform会使用相同的主成分
  File "main.py", line 341, in fit_transform
    self.fit(X)
  File "main.py", line 293, in fit
    covariance_matrix = cp.cov(X_centered, rowvar=False)
  File "/home/lzy/.conda/envs/ltf/lib/python3.8/site-packages/cupy/_statistics/correlation.py", line 210, in cov
    out = X.dot(X_T.conj()) * (1 / cupy.float64(fact))
  File "cupy/_core/core.pyx", line 1761, in cupy._core.core._ndarray_base.dot
  File "cupy/_core/_routines_linalg.pyx", line 540, in cupy._core._routines_linalg.dot
  File "cupy/_core/_routines_linalg.pyx", line 600, in cupy._core._routines_linalg.tensordot_core
  File "cupy/_core/core.pyx", line 2779, in cupy._core.core._ndarray_init
  File "cupy/_core/core.pyx", line 237, in cupy._core.core._ndarray_base._init_fast
  File "cupy/cuda/memory.pyx", line 740, in cupy.cuda.memory.alloc
  File "cupy/cuda/memory.pyx", line 1426, in cupy.cuda.memory.MemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 1447, in cupy.cuda.memory.MemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 1118, in cupy.cuda.memory.SingleDeviceMemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 1139, in cupy.cuda.memory.SingleDeviceMemoryPool._malloc
  File "cupy/cuda/memory.pyx", line 1384, in cupy.cuda.memory.SingleDeviceMemoryPool._try_malloc
  File "cupy/cuda/memory.pyx", line 1387, in cupy.cuda.memory.SingleDeviceMemoryPool._try_malloc
cupy.cuda.memory.OutOfMemoryError: Out of memory allocating 58,901,832,110,973,952 bytes (allocated so far: 4,805,156,352 bytes).
TimeList:
00: Start | 2024.07.10-16:32:27
01: init accuracy: 10.20% | 2024.07.10-16:32:36
02: Round 1 of 32 | 2024.07.10-16:32:36